# Generated by Django 4.2 on 2024-12-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wartsila_engine',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('component_name', models.CharField(max_length=100)),
                ('pdf_page', models.PositiveBigIntegerField(default=1)),
                ('engine', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='spare_parts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('part_id', models.CharField(blank=True, max_length=10, null=True)),
                ('part_name', models.CharField(max_length=255)),
                ('pdf_page', models.PositiveBigIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=100)),
                ('extras', models.CharField(blank=True, max_length=255, null=True)),
                ('isAvalable', models.CharField(blank=True, default='Currently in Storage', max_length=255, null=True)),
                ('component_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.wartsila_engine')),
            ],
        ),
    ]
